app: # RESTful
  name: "wealth-bond-quote-service"
  mode: debug # server mode: release, debug, test
  addr: ":8081"
  ver: "0.0.1"
  prefork: false

log:
  path: "/data/logs/wealth-bond-quote-service/wealth-bond-quote-service.log"
  level: "debug"
  size: 1073741824
  count: 10

# 亚丁ATS系统配置
adenATS:
  baseURL: "https://adenapi.cstm.adenfin.com"
  wssURL: "wss://adenapi.cstm.adenfin.com/message-gateway/message/atsapi/ws"
  username: "ATSTEST10001"
  password: "Abc12345"
  smsCode: "1234"
  clientId: "30021"
  publicKey: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCTCY4u102mtUlVEyUMlXOkflPLdWN+ez5IDcLiNzw2ZkiEY17U4lk8iMx7yTEO/ZWCKIEdQV+U6tplJ98X3I/Py/DzWd1L7IPE6mZgclfcXg+P4ocaHPsKgAodc4G1W9jTu2d6obL3d33USCD0soGYE6fkf8hk7EPKhgNf4iUPCwIDAQAB"
  # 连接配置
  timeout: 30 # 连接超时时间（秒）
  heartbeat: 20000 # 心跳间隔（毫秒）
  reconnectInterval: 5000 # 重连间隔（毫秒）
  maxReconnectAttempts: 10 # 最大重连次数

# 数据处理配置
dataProcess:
  # 缓冲区配置
  rawBufferSize: 20000    # 原始数据缓冲区大小
  parsedBufferSize: 4000  # 解析后数据缓冲区大小
  deadBufferSize: 1000    # 死信队列缓冲区大小
  # 工作线程配置
  workerNum: 8            # 数据处理工作线程数
  parserWorkerNum: 4      # 数据解析工作线程数
  dbWorkerNum: 2          # 数据库写入工作线程数
  # 批处理配置
  batchSize: 300          # 批处理大小
  flushDelayMs: 100       # 刷新延迟（毫秒）
  # 数据清理配置
  dataRetentionDays: 30   # 数据保留天数
  cleanupIntervalHours: 24 # 清理任务执行间隔（小时）

# 文件导出配置
export:
  path: "/data/export/bond_quote"
  urlPrefix: "http://localhost:8081/export"
  retentionDays: 7

# MySQL配置
# mysql:
#   fund:
#     user: "fund_user"
#     password: "fund_pass"
#     host: "localhost"
#     port: "3306"
#     schema: "fund_db"
#   bond:
#     user: "bond_user"
#     password: "bond_pass"
#     host: "localhost"
#     port: "3306"
#     schema: "bond_db"

# mysqlDBPool:
#   maxIdleConn: 10
#   maxOpenConn: 100
#   connMaxLifetime: 600